apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
spec:
  selector:
    matchLabels:
      app: api-app
  replicas: 2
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app
          image: docker.io/205618929/api-app:e65f2a7327e35e80d9e4bbb0c88dea7ab6829736
          ports:
            - containerPort: 8080
