apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
spec:
  selector:
    matchLabels:
      app: api-app
  replicas: 2
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app
          image: docker.io/205618929/my-app:8b031943c01a645233dfec4ded4dd5c834dd3b72
          ports:
            - containerPort: 8080
