name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          image="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}"
          docker build -t $image .
          docker push $image

      - name: Update manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dev
          yq e -i '.spec.template.spec.containers[0].image = "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}"' deployment.yaml
          git config --global user.name "ci"
          git config --global user.email "ci@@users.noreply.github.com"
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main