name: CI

on:
  push:
    branches: [argocd-apps-config]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          image="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/api-app:${{ github.sha }}"
          docker build -t $image .
          docker push $image

      - name: Checkout Argo apps config repo
        uses: actions/checkout@v4
        with:
          repository: MayCesana/argocd-apps-config
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update Manifest
        env:
          ENV: dev
        run: |
          cd argocd-apps-config/apps/api-app/$ENV
          yq e -i '.spec.template.spec.containers[0].image = "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/api-app:${{ github.sha }}"' deployment.yaml

      - name: Commit and Push Changes
        run: |
          cd argocd-apps-config
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main